use tienda;
SELECT nombre FROM tienda.producto;
SELECT nombre, precio FROM tienda.producto;
SELECT * FROM tienda.producto;
SELECT nombre, precio, precio*1.2033 as 'precio(usd)' FROM tienda.producto;
SELECT nombre as 'nom de producto', precio as 'euro', precio*1.2033 as 'dolars' FROM tienda.producto;
SELECT UPPER(nombre), precio FROM tienda.producto;
SELECT LOWER(nombre), precio FROM tienda.producto;
SELECT nombre, SUBSTR(UPPER(nombre),1,2) FROM tienda.fabricante; 
SELECT nombre, round(precio) FROM tienda.producto; 
SELECT nombre, truncate(precio,0) FROM tienda.producto; 
SELECT fabricante.codigo FROM tienda.fabricante INNER JOIN tienda.producto on fabricante.codigo = producto.codigo_fabricante; 
SELECT distinct fabricante.codigo FROM tienda.fabricante INNER JOIN tienda.producto on fabricante.codigo = producto.codigo_fabricante; 
SELECT nombre FROM tienda.fabricante order by nombre asc; 
SELECT nombre FROM tienda.fabricante order by nombre desc; 
SELECT nombre, precio FROM tienda.producto order by nombre asc, precio desc; 
SELECT * FROM tienda.fabricante limit 5;
SELECT * FROM tienda.fabricante limit 3,2;
SELECT nombre, precio FROM tienda.producto order by precio asc limit 1;
SELECT nombre, precio FROM tienda.producto order by precio desc limit 1;
SELECT producto.nombre, codigo_fabricante FROM tienda.producto join tienda.fabricante on producto.codigo_fabricante = fabricante.codigo where codigo_fabricante = 2;
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto join tienda.fabricante on producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre, precio, fabricante.nombre FROM tienda.producto join tienda.fabricante on producto.codigo_fabricante = fabricante.codigo order by fabricante.nombre asc;
